# I - Python Exercices

1. Create two integer variables named `a` and `b`, print the product of the two variables.

In [97]:
a = 1
b = 2
print(a+b)

3


2. Create two float variables named `a` and `b`, print the sum of the two variables.

In [98]:
a = 1.0
b = 2.0
print(a+b)

3.0


3. Assign your first name to the variable named `a`, and your surname to the variable named `b` as strings. Then, merge these two string variables and assign it to the variable named `c`, and print.

In [99]:
a = "H"
b = "X"
print(a+b)
print("".join([a, b]))

HX
HX


4. Create a list named `list_numbers` containing the number 10, 165, 842, 9, 3, 651 and print the 3rd and last element of this list.

In [100]:
ln = [10,165,842,9,3,651]
print(ln[2],ln[-1])

842 651


5. Using a `for` loop, print each element of the previous list (`list_numbers`).

In [101]:
for i in ln:
    print(i)

10
165
842
9
3
651


6. Using a `for` loop, print only the odd number of the previous list (`list_numbers`).

the modulo `%` operation between **a** and **b** return the remainder of the euclidean division between **a** and **b**

In [102]:
print(ln[1::2])
'''
for i in ln:
    if i % 2 != 0:
        output.append(num)
print(output)
'''

[165, 9, 651]


'\nfor i in ln:\n    if i % 2 != 0:\n        output.append(num)\nprint(output)\n'

7. Using a `for` loop, store the squared values from 0 to 10 in a list call `list_square`.

   hint: you need to initiate an empty list first.

In [103]:
ls = []
for i in range(10):
    ls.append(i*i)
print(ls)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


8. Using only one `for` loop, write a code that stores all the odd numbers in a list named `list_odds` and the even numbers in a list named `list_evens`. The loop must start from 1 and goes up to n=100.

In [104]:
lo=[]
le=[]
for i in range(100):
    if i % 2 == 0:
        lo.append(i+1)
    else:
        le.append(i+1)
print(lo)
print(le)        

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


9. Write a function `exponent` that take two integers as an input, named `base` and `exp`, and return `base` raises to the power of `exp`. Print the result for base=2, exp=5 and base=3, exp=4

In [105]:
def exp(base, power):
    return base**power
print(exp(2,5))
print(exp(3,4))

32
81


10. Write a function that takes as input three variables, and returns the largest of the three. Do this without using the Python max() function!

In [106]:
def mo3(n1,n2,n3):
    if n1 > n2 and n1 > n3:
        return n1
    elif n2 > n1 and n2 > n3:
        return n2
    else:
        return n3 
print(mo3(1,2,3))
print(mo3(2,3,1))
print(mo3(3,1,2))

3
3
3


11. (bonus) The Fibonacci sequence is define as: $F_i$ = $F_{i-1}$ + $F_{i-2}$. The sequence start with $F_0 = 1$ and $F_1$=1.

    Write a function that take `n` as an input and return $F_n$.

In [107]:
def fib(n):
    Fib=[]
    Fib.append(1)
    Fib.append(1)
    for i in range(2,n+1):
        Fib.append(Fib[i-1]+Fib[i-2])
    return Fib[n]

print(fib(12))

233


# II - Numpy

NumPy is a third-party package for Python that provides utilities for numerical programming with Python. It is commonly imported via

In [108]:
import numpy as np

The Python programming language was not originally designed for numerical computing, so when you try to add two `list`, python will concatenate them instead of doing elementwise addition

In [109]:
a = [0, 1, 2]
b = [3, 4, 5]
c = a + b
print(c)

[0, 1, 2, 3, 4, 5]


In order to sum element of two list, you need to loop through all the elements of each `list`

In [110]:
c = []
for i in range(len(a)):
    c.append(a[i] + b[i])
print(c)

[3, 5, 7]


This is really not efficient in term of memory and computation time. This is why numpy was developp with the idea of using **array** to store numbers and make manipulation/computation easy.

To create an array, you can simply call that `array` methods on any `list`:

In [111]:
my_array = np.array([0, 1, 2]) # create a 1D array of integers
print(my_array)

[0 1 2]


In [112]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c1 = a + b
print(c1)

c2 = []
for i in range(len(a)):
    c2.append(a[i] + b[i])
print(c2)

c3=[]
for i in range(len(a)):
    c3=np.append(c3,a[i] + b[i])
print(c3)

[3 5 7]
[3, 5, 7]
[3. 5. 7.]


In [113]:
c2 == c3

array([ True,  True,  True])

You will often see the name `ndarray` on the internet when searching for numpy array. This is for **n-dimensional array** which mean that Numpy support **n** dimension for the array.


$\left[
\begin{array}{ccc}
 0 & 1 & 2 \\
 3 & 4 & 5 \end{array}
\right]$



You can create a 2D array in Numpy like this:

In [114]:
my_2D_array = np.array([[0, 1, 2], [3, 4 ,5]])
print(my_2D_array)

[[0 1 2]
 [3 4 5]]


In [115]:
list_2D = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
array_2D = np.array(list_2D)
print('2D list in python:\n', list_2D, '\n')
print('2D array in Numpy:\n', array_2D)

2D list in python:
 [[0, 1, 2], [3, 4, 5], [6, 7, 8]] 

2D array in Numpy:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


Numpy support slicing. Slicing refers to extracting partial data from arrays.



$
\begin{array}{cc} &
\begin{array}{cccc} 0 & 1 & 2 & 3
\end{array}
\\
\begin{array}{cccc}
0 \\
1 \\
2 \\
3
\end{array}
&
\left(
\begin{array}{cccc}
a & b & c & d \\
e & f & g & h \\
i & j & k & l \\
m & n & o & p \end{array}
\right)
\end{array}
$



In [116]:
letter_list = [['a','b','c','d'],['e','f','g','h'],['i','j','k','l'],['m','n','o','p']]
letter_array = np.array(letter_list)
print(letter_array)

[['a' 'b' 'c' 'd']
 ['e' 'f' 'g' 'h']
 ['i' 'j' 'k' 'l']
 ['m' 'n' 'o' 'p']]


In [117]:
print(letter_array[0, 2]) # python indexing start at 0

print(letter_array[:, 1]) # get all the values from the 2nd column

c
['b' 'f' 'j' 'n']


Doing the same thing on list require to iterate through all the elements:

In [118]:
column = []
for sublist in letter_list:
    column.append(sublist[1])
print(column)

# Return a copy of the 2nd array collapsed into one dimension.
letter_array[:, 1] 

['b', 'f', 'j', 'n']


array(['b', 'f', 'j', 'n'], dtype='<U1')

In [119]:
#Return the 2nd column in form of a 2D array.
letter_array[:, :1] 

array([['a'],
       ['e'],
       ['i'],
       ['m']], dtype='<U1')

## Build-in function

Numpy comes with a lot of usefull build-in function to make operation on array easy.

### 1 - zeros, ones and full

It is not always necessary to create an array from a list. Numpy can directly create one for you.
By using `np.zeros()`, `np.ones()` or `np.full()`, you can create an array fill with zeros, ones or any specify value. You can specify the shape by using the `shape` argument

In [120]:
zero = np.zeros(shape=(3, 2),dtype=float)
print("The 'zeros' array:\n", zero)

one = np.ones(shape=(2,4))
print("\nThe 'ones' array:\n", one)

full = np.full(shape=(3,2,2), fill_value=6,dtype=float)
print("\nThe 'full' array:\n", full)

The 'zeros' array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]

The 'ones' array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

The 'full' array:
 [[[6. 6.]
  [6. 6.]]

 [[6. 6.]
  [6. 6.]]

 [[6. 6.]
  [6. 6.]]]


### 2 - linspace and arange

If you need to create an array with a specific sequence, you can use `np.linspace` or `np.arange`.

`linspace` takes 3 arguments: a **start**ing point, a **stop**ing and the **num**ber of values you want between those two points

In [121]:
linspace_sequence = np.linspace(start=1, stop=9, num=9)
print('linspace:\n', linspace_sequence)

linspace:
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]


`arange` also takes 3 arguments: a **start**ing point, a **stop**ing but the $3^{rd}$ argument is the **step** size (who much should you increase between two consecutive value inside the array.

In [122]:
arange_sequence = np.arange(start=0, stop=5, step=0.5) # arange do not include the stoping point!
print('arange\n', arange_sequence)

arange
 [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


### 3 - shape

you can access the shape of an array by using the `shape()` methods from `numpy`

In [123]:
print('shape of the array is:\n', np.shape(array_2D))

# a more compact version, which give similar result is:
print('\nCompact version:\n', array_2D.shape)

shape of the array is:
 (3, 3)

Compact version:
 (3, 3)


### 4 - reshape

`np.reshape()` will give a new shape to an array without changing its data. The new shape must be compatible with the original shape. 

In [124]:
print('origine shape:', linspace_sequence.shape)
print('original array:\n', linspace_sequence)

reshape_array = np.reshape(linspace_sequence, newshape=(3, 3))
print('\nnew shape:', reshape_array.shape)
print('new array:\n', reshape_array)

origine shape: (9,)
original array:
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]

new shape: (3, 3)
new array:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### 5 - min and max

Return the min or max of the array.

In [125]:
print('The min value is: ', np.min(array_2D))
print('The max value is: ', array_2D.max())

The min value is:  0
The max value is:  8


### 6 - mean and standard deviation


you can easily get the mean of an array by simply using `np.mean()`. If no arguments is specify, it will compute the mean of all the element in the array. Similarly, you can compute the standard deviation by using `np.std()`

In [126]:
print('original 2D array:\n', array_2D, '\n')

print('mean =', np.mean(array_2D))
print('std. dev. =', np.std(array_2D))

original 2D array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

mean = 4.0
std. dev. = 2.581988897471611


### 7 - square root

By using the `np.sqrt()` method, you can compute the element-wise square root of an array:

In [127]:
np.sqrt(array_2D)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

### 8 - dot

`np.dot()` return the dot product between two arrays

$$
\begin{pmatrix}
    a & b\\
    c & d
\end{pmatrix}
\cdot
\begin{pmatrix}
    e & f\\
    g & h
\end{pmatrix}
=
\begin{pmatrix}
    ae + bg & af + bh\\
    ce + dg & cf + dh 
\end{pmatrix}
$$

In [128]:
a =   np.arange(1, 5, 1).reshape(2, 2)
b = np.linspace(5, 8, 4).reshape(2, 2)
print('1st array:\n', a)
print('\n2nd array:\n', b)

c = np.dot(a,b)
print('\ndot product array:\n', c)

1st array:
 [[1 2]
 [3 4]]

2nd array:
 [[5. 6.]
 [7. 8.]]

dot product array:
 [[19. 22.]
 [43. 50.]]


## Exercices:

1. Create an array, call `big`, ranging from 0 to 100 and uniformily space with 6 elements in it, 

2. Create an array, call `small`, ranging from 10 to 0 with a step size of 2. you must include the starting and stoping points

3. Reshape `big` with 3 rows and 2 columns and reshape `small` with 2 columns and 3 rows

4. Compute the dot product between `big` and `small` call `prod`

5. Print the min and max of each rows

6. Using a for loop, compute the mean of the square root of `prod`, without using the build-in function from numpy and compare the results when using numpy

In [131]:
big = np.linspace(0,100,6)
print(big)

small = np.arange(10,0,-2)
small = np.append(small,0)
print(small)

rsbig = np.reshape(big,(3,2))
print(rsbig)
resmall = np.reshape(small,(2,3))
print(resmall)

prod= np.dot(rsbig,resmall)
print(prod)


maxm = np.max(prod, axis=1)
minm = np.min(prod, axis=1)
print('max:', maxm)
print('min:', minm)

total_sqrt = 0
num_elements = prod.size
rprod = np.reshape(prod, 9)
for value in rprod:
    total_sqrt += np.sqrt(value)
manual_mean_sqrt = total_sqrt / num_elements

numpy_mean_sqrt = np.mean(np.sqrt(prod))

print("Manual calculation of mean square root:", manual_mean_sqrt)
print("NumPy calculation of mean square root:", numpy_mean_sqrt)


[  0.  20.  40.  60.  80. 100.]
[10  8  6  4  2  0]
[[  0.  20.]
 [ 40.  60.]
 [ 80. 100.]]
[[10  8  6]
 [ 4  2  0]]
[[  80.   40.    0.]
 [ 640.  440.  240.]
 [1200.  840.  480.]]
max: [  80.  640. 1200.]
min: [  0. 240. 480.]
Manual calculation of mean square root: 18.063092311542082
NumPy calculation of mean square root: 18.063092311542082
